### ISSUE TITLE
Looking for Hand-Labeled Data?

### ISSUE THREAD

**Issue by EvanOman** [rcrupiISP/SiameseDisambiguation#1]
Hello! I am very interested in your work, very well done!

One question: in your[ excellent paper ](https://arxiv.org/pdf/2303.05391v1.pdf) you reference a hand-labeled dataset of company name pairs. Is this dataset in the repo somewhere? I could only find the acronym data.

Let me know, thanks!

**Comment by rcrupiISP** [comment]
Hello, Evan. Thank you for your interest shown in this project.
Unfortunately, due to confidentiality and privacy issues, we were unable to share the hand-labeled dataset.

Thanks again,

Riccardo Crupi

**Comment by EvanOman** [comment]
No problem, thanks for getting back to me Riccardo!
